const BUILTIN = window.ECHO_QUESTIONS || [];
const STORAGE_KEY = 'echo-board-progress-v3';
const CUSTOM_KEY = 'echo-board-custom-questions-v3';
const state = {mode:null,questions:[],index:0,answers:[],secondsPerQuestion:60,remaining:60,timerId:null,selectedCategories:new Set(),difficulty:'all',desiredCount:10,sessionStartedAt:0,questionStartedAt:0,reviewIds:null};
const $=id=>document.getElementById(id); const letters=['A','B','C','D','E','F','G'];
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function customQuestions(){try{return JSON.parse(localStorage.getItem(CUSTOM_KEY)||'[]')}catch{return []}}
function allQuestions(){return [...BUILTIN,...customQuestions()]}
function loadProgress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}}
function saveProgress(p){localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}
function recordAnswer(q,correct,timeSpent,selected){const p=loadProgress();p.records=p.records||{};const r=p.records[q.id]||{attempts:0,correct:0,wrong:0,last:null};r.attempts++;r.last=correct?'correct':'wrong';r.lastSelected=selected;r.lastTime=timeSpent;correct?r.correct++:r.wrong++;p.records[q.id]=r;saveProgress(p)}
function statusOf(q){const r=loadProgress().records?.[q.id];return r?.last||'unseen'}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'instant'});if(id==='homeView')updateDashboard();if(id==='bankView')renderBank()}
function formatTime(s){s=Math.max(0,Math.round(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function categories(){return [...new Set(allQuestions().map(q=>q.category))].sort()}
function updateDashboard(){const qs=allQuestions(),p=loadProgress(),records=p.records||{},seen=Object.values(records).filter(r=>r.attempts);const answered=seen.reduce((n,r)=>n+r.attempts,0),correct=seen.reduce((n,r)=>n+r.correct,0),wrong=seen.reduce((n,r)=>n+r.wrong,0);$('statAnswered').textContent=answered;$('statCorrect').textContent=correct;$('statWrong').textContent=wrong;$('statAccuracy').textContent=answered?Math.round(correct/answered*100)+'%':'—';$('heroQuestionCount').textContent=qs.length;$('wrongCountText').textContent=qs.filter(q=>statusOf(q)==='wrong').length+' questions';$('correctCountText').textContent=qs.filter(q=>statusOf(q)==='correct').length+' questions';const map={};qs.forEach(q=>{if(records[q.id]?.attempts){map[q.category]??={a:0,c:0};map[q.category].a+=records[q.id].attempts;map[q.category].c+=records[q.id].correct}});$('categoryPreview').innerHTML=Object.keys(map).length?Object.entries(map).sort((a,b)=>a[0].localeCompare(b[0])).map(([cat,x])=>{const pct=Math.round(x.c/x.a*100);return `<div class="cat-row"><div><div class="cat-name">${esc(cat)} <span style="color:#64758d">(${x.c}/${x.a})</span></div><div class="cat-track"><div class="cat-fill" style="width:${pct}%"></div></div></div><div class="cat-score">${pct}%</div></div>`}).join(''):'<div class="empty">Aún no hay rendimiento por categoría.</div>'}
function openSetup(mode,reviewIds=null){state.mode=mode;state.reviewIds=reviewIds;state.selectedCategories=new Set();state.difficulty='all';state.desiredCount=Math.min(10,allQuestions().length);$('setupEyebrow').textContent=mode==='training'?'TRAINING MODE':'REAL TEST';$('setupTitle').textContent=mode==='training'?'Build your session':'Simulate the board';$('setupDescription').textContent=mode==='training'?'Feedback inmediato, explicación de las cuatro opciones y guardado automático.':'Examen cronometrado: 60 segundos por pregunta, sin feedback hasta finalizar.';renderCategoryFilters();$('trainingTimeGrid').style.display=mode==='training'?'grid':'none';$('testTimeInfo').textContent=mode==='training'?'Choose your pace.':'Test timing: 60 seconds per question.';updateCount();showView('setupView')}
function renderCategoryFilters(){const cs=categories();$('categoryFilters').innerHTML='<button class="chip active" data-cat="all">All</button>'+cs.map(c=>`<button class="chip" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$('categoryFilters').querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{if(b.dataset.cat==='all'){state.selectedCategories.clear();$('categoryFilters').querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active')}else{document.querySelector('[data-cat="all"]').classList.remove('active');state.selectedCategories.has(b.dataset.cat)?state.selectedCategories.delete(b.dataset.cat):state.selectedCategories.add(b.dataset.cat);b.classList.toggle('active',state.selectedCategories.has(b.dataset.cat));if(!state.selectedCategories.size)document.querySelector('[data-cat="all"]').classList.add('active')}updateCount()})}
function updateCount(){const n=filteredQuestions().length;state.desiredCount=Math.max(1,Math.min(state.desiredCount,n||1));$('questionCount').textContent=state.desiredCount}
function filteredQuestions(){let qs=allQuestions();if(state.reviewIds)qs=qs.filter(q=>state.reviewIds.includes(q.id));if(state.selectedCategories.size)qs=qs.filter(q=>state.selectedCategories.has(q.category));if(state.difficulty!=='all')qs=qs.filter(q=>q.difficulty===state.difficulty);return qs}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startSession(){let qs=filteredQuestions();if(!qs.length){alert('No hay preguntas con estos filtros.');return}qs=shuffle(qs).slice(0,state.desiredCount);state.questions=qs;state.index=0;state.answers=[];state.sessionStartedAt=Date.now();state.secondsPerQuestion=state.mode==='test'?60:state.secondsPerQuestion;showView('quizView');renderQuestion();startTimer()}
function startTimer(){clearInterval(state.timerId);state.remaining=state.secondsPerQuestion;state.questionStartedAt=Date.now();updateTimer();state.timerId=setInterval(()=>{state.remaining--;updateTimer();if(state.remaining<=0){clearInterval(state.timerId);timeOut()}},1000)}
function updateTimer(){const t=$('timer');t.textContent=formatTime(state.remaining);t.classList.toggle('warning',state.remaining<=20&&state.remaining>10);t.classList.toggle('danger',state.remaining<=10)}
function timeOut(){if(state.mode==='training'){answerQuestion(null,true)}else{submitCurrent(null,true)}}
function renderQuestion(){const q=state.questions[state.index];if(!q)return;const answered=state.answers[state.index];$('modeBadge').textContent=state.mode==='training'?'TRAINING':'REAL TEST';$('progressText').textContent=`${state.index+1} / ${state.questions.length}`;$('progressBar').style.width=((state.index)/state.questions.length*100)+'%';$('categoryTag').textContent=q.category;$('difficultyTag').textContent=q.difficulty;$('questionId').textContent=q.id;$('questionText').textContent=q.question;$('feedback').classList.add('hidden');$('nextBtn').disabled=true;$('skipBtn').disabled=false;$('options').innerHTML=q.options.map((o,i)=>`<button class="option" data-i="${i}"><span class="option-letter">${letters[i]}</span><span class="option-copy">${esc(o.text)}</span></button>`).join('');$('options').querySelectorAll('.option').forEach(b=>b.onclick=()=>answerQuestion(Number(b.dataset.i),false));if(answered)restoreAnswer(answered);startTimer()}
function restoreAnswer(a){const btns=[...$('options').querySelectorAll('.option')];btns.forEach((b,i)=>{b.disabled=true;b.classList.toggle('correct',i===state.questions[state.index].answer);b.classList.toggle('incorrect',i===a.selected&&i!==state.questions[state.index].answer)});$('nextBtn').disabled=false;if(state.mode==='training')showFeedback(state.questions[state.index],a.selected)}
function answerQuestion(selected,timedOut=false){if(state.answers[state.index])return;const q=state.questions[state.index],timeSpent=Math.min(state.secondsPerQuestion,Math.max(0,Math.round((Date.now()-state.questionStartedAt)/1000)));const correct=selected!==null&&selected===q.answer;state.answers[state.index]={selected,correct,timeSpent};recordAnswer(q,correct,timeSpent,selected);clearInterval(state.timerId);[...$('options').querySelectorAll('.option')].forEach((b,i)=>{b.disabled=true;b.classList.toggle('correct',i===q.answer);b.classList.toggle('incorrect',i===selected&&i!==q.answer)});$('nextBtn').disabled=false;$('skipBtn').disabled=true;if(state.mode==='training'){showFeedback(q,selected,timedOut)}else if(timedOut){nextQuestion()}}
function submitCurrent(selected,timedOut){if(state.answers[state.index])return;const q=state.questions[state.index],timeSpent=selected===null?state.secondsPerQuestion:Math.round((Date.now()-state.questionStartedAt)/1000),correct=selected!==null&&selected===q.answer;state.answers[state.index]={selected,correct,timeSpent};recordAnswer(q,correct,timeSpent,selected);if(timedOut)nextQuestion()}
function showFeedback(q,selected,timedOut){const title=timedOut?'Time expired':selected===q.answer?'Correct':'Incorrect';$('feedback').innerHTML=`<div class="feedback-title">${title} · ${q.concept||'Key concept'}</div><div class="feedback-grid">${q.options.map((o,i)=>`<div class="feedback-item ${i===q.answer?'correct':''} ${i===selected&&i!==q.answer?'user-wrong':''}"><strong>${letters[i]} · ${i===q.answer?'CORRECT ANSWER':'OPTION'}</strong><p>${esc(o.explanation)}</p></div>`).join('')}</div>`;$('feedback').classList.remove('hidden')}
function nextQuestion(){if(state.index>=state.questions.length-1){finishSession();return}state.index++;renderQuestion()}
function finishSession(){clearInterval(state.timerId);state.elapsed=Math.round((Date.now()-state.sessionStartedAt)/1000);showResults()}
function showResults(){const total=state.questions.length,correct=state.answers.filter(a=>a?.correct).length,wrong=state.answers.filter(a=>a&&!a.correct).length,unanswered=total-correct-wrong,pct=Math.round(correct/total*100);$('resultsTitle').textContent=state.mode==='training'?'Training complete':'Test complete';$('scorePercent').textContent=pct+'%';$('scoreRing')?.style.setProperty('--score',pct+'%');$('resultCorrect').textContent=correct;$('resultWrong').textContent=wrong;$('resultUnanswered').textContent=unanswered;$('resultTime').textContent=formatTime(state.elapsed);const map={};state.questions.forEach((q,i)=>{map[q.category]??={total:0,correct:0};map[q.category].total++;if(state.answers[i]?.correct)map[q.category].correct++});$('categoryResults').innerHTML=Object.entries(map).map(([cat,c])=>{const p=Math.round(c.correct/c.total*100);return `<div class="cat-row"><div><div class="cat-name">${esc(cat)} <span style="color:#64758d">(${c.correct}/${c.total})</span></div><div class="cat-track"><div class="cat-fill" style="width:${p}%"></div></div></div><div class="cat-score">${p}%</div></div>`}).join('');$('questionResults').innerHTML=state.questions.map((q,i)=>{const a=state.answers[i],good=a?.correct,icon=good?'✓':'×';return `<div class="review-item"><span class="review-icon ${good?'good':'bad'}">${icon}</span><span class="review-q">${i+1}. ${esc(q.question)}</span><span class="review-time">${a?.timeSpent??0}s</span></div>`}).join('');showView('resultsView')}
function renderBank(){const qs=allQuestions(),p=loadProgress(),records=p.records||{};$('bankTotal').textContent=qs.length;$('bankCustom').textContent=customQuestions().length;$('bankWrong').textContent=qs.filter(q=>records[q.id]?.last==='wrong').length;$('bankCorrect').textContent=qs.filter(q=>records[q.id]?.last==='correct').length;const select=$('bankCategory'),cur=select.value;select.innerHTML='<option value="all">All categories</option>'+categories().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');select.value=categories().includes(cur)?cur:'all';const search=$('bankSearch').value.toLowerCase().trim(),cat=select.value,status=$('bankStatus').value;const filtered=qs.filter(q=>{const hit=!search||`${q.id} ${q.question} ${q.concept} ${q.category}`.toLowerCase().includes(search);return hit&&(cat==='all'||q.category===cat)&&(status==='all'||statusOf(q)===status)});$('bankList').innerHTML=filtered.length?filtered.map(q=>{const st=statusOf(q);return `<div class="bank-item"><div class="bank-badge">${esc(q.id)}</div><div><div class="bank-title">${esc(q.question)}</div><div class="bank-meta">${esc(q.category)} · ${esc(q.difficulty)} · ${st==='wrong'?'Needs review':st==='correct'?'Correct':'Unseen'}</div></div><div class="bank-item-actions"><button class="mini" data-review="${esc(q.id)}">Practice</button></div></div>`}).join(''):'<div class="empty">No questions match your filters.</div>';document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>startReview(b.dataset.review))}
function startReview(id){state.mode='training';state.reviewIds=[id];state.selectedCategories.clear();state.difficulty='all';state.desiredCount=1;state.secondsPerQuestion=60;startSession()}
function exportBank(){const payload={version:3,createdAt:new Date().toISOString(),questions:allQuestions()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='echo-board-question-bank-v3.json';a.click();URL.revokeObjectURL(a.href)}
function importBank(file){const reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result),incoming=Array.isArray(raw)?raw:raw.questions;if(!Array.isArray(incoming))throw Error('Formato inválido');const valid=incoming.filter(validQuestion);const existing=customQuestions(),map=new Map([...existing,...valid].map(q=>[q.id,q]));localStorage.setItem(CUSTOM_KEY,JSON.stringify([...map.values()]));alert(`${valid.length} preguntas importadas/actualizadas.`);renderBank();updateDashboard()}catch(e){alert('No se pudo importar: '+e.message)}};reader.readAsText(file)}
function validQuestion(q){return q&&q.id&&q.category&&q.difficulty&&q.question&&Array.isArray(q.options)&&q.options.length>=3&&q.options.length<=7&&q.options.every(o=>o.text&&o.explanation)&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4}
function renderOptionEditor(n=4){n=Math.max(3,Math.min(7,Number(n)||4));$('optionEditor').innerHTML=letters.slice(0,n).map(l=>`<div class="option-row"><span>${l}</span><input data-opt-text="${l}" placeholder="Option ${l}" required><input data-opt-exp="${l}" placeholder="Why is this option correct/incorrect?" required></div>`).join('');$('answerSelect').innerHTML=letters.slice(0,n).map((l,i)=>`<option value="${i}">${l}</option>`).join('')}
function openModal(){const id='CUSTOM-'+String(customQuestions().length+1).padStart(3,'0');$('questionForm').reset();$('questionForm').elements.id.value=id;$('optionCount').value='4';renderOptionEditor(4);$('questionModal').classList.remove('hidden')}
function closeModal(){$('questionModal').classList.add('hidden')}
$('beginSession').onclick=startSession;$('setupBack').onclick=()=>showView('homeView');$('quizQuit').onclick=()=>{clearInterval(state.timerId);showView('homeView')};$('skipBtn').onclick=()=>{if(state.mode==='training')answerQuestion(null,false);else submitCurrent(null,false);if(state.mode==='training'){}else nextQuestion()};$('nextBtn').onclick=nextQuestion;$('resultsHome').onclick=()=>showView('homeView');$('resultsAgain').onclick=()=>openSetup(state.mode);$('countMinus').onclick=()=>{state.desiredCount--;updateCount()};$('countPlus').onclick=()=>{state.desiredCount++;updateCount()};document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{state.difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(x=>x.classList.toggle('active',x===b));updateCount()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>openSetup(b.dataset.mode));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('reviewWrong').onclick=()=>{const ids=allQuestions().filter(q=>statusOf(q)==='wrong').map(q=>q.id);ids.length?openSetup('training',ids):alert('No hay preguntas incorrectas guardadas.')};$('reviewCorrect').onclick=()=>{const ids=allQuestions().filter(q=>statusOf(q)==='correct').map(q=>q.id);ids.length?openSetup('training',ids):alert('No hay preguntas correctas guardadas.')};$('resetProgress').onclick=()=>{if(confirm('Reset all progress and custom questions?')){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(CUSTOM_KEY);updateDashboard();renderBank()}};$('toggleTheme').onclick=()=>document.body.classList.toggle('light');$('bankSearch').oninput=renderBank;$('bankCategory').onchange=renderBank;$('bankStatus').onchange=renderBank;$('openAddQuestion').onclick=openModal;$('closeQuestionModal').onclick=closeModal;$('importBankBtn').onclick=()=>$('importBankInput').click();$('importBankInput').onchange=e=>e.target.files[0]&&importBank(e.target.files[0]);$('exportBank').onclick=exportBank;$('questionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),n=Number(f.get('optionCount')||4),opts=letters.slice(0,n).map(l=>({text:document.querySelector(`[data-opt-text="${l}"]`).value.trim(),explanation:document.querySelector(`[data-opt-exp="${l}"]`).value.trim()}));const q={id:f.get('id').trim(),category:f.get('category').trim(),difficulty:f.get('difficulty'),question:f.get('question').trim(),options:opts,answer:Number(f.get('answer')),concept:f.get('concept').trim()||'Custom question',sourceNote:'User-added question'};if(allQuestions().some(x=>x.id===q.id)){alert('Ese ID ya existe. Usa otro ID.');return}const arr=customQuestions();arr.push(q);localStorage.setItem(CUSTOM_KEY,JSON.stringify(arr));closeModal();renderBank();updateDashboard()};
document.querySelectorAll('.time-option').forEach(b=>b.onclick=()=>{state.secondsPerQuestion=Number(b.dataset.seconds);document.querySelectorAll('.time-option').forEach(x=>x.classList.toggle('active',x===b))});
$('optionCount').onchange=e=>renderOptionEditor(Number(e.target.value));updateDashboard();renderBank();
